//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeGrab.Models
{
    using System;
    using System.Collections.Generic;

    public partial class HistoryPost
    {
        public int Id { get; set; }
        public int NewsId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime DatePost { get; set; }
        public Nullable<int> View { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime DateUpdate { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual News News { get; set; }
    }
}
