//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeGrab.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Photo
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> NewsId { get; set; }
        public System.DateTime DateCreate { get; set; }

        public virtual News News { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
